export interface Recipe {
  id: string;
  title: string;
  category: string;
  time: string;
  difficulty: "Easy" | "Medium" | "Hard";
  rating: number;
  servings: number;
  image: string;
  description: string;
  ingredients: string[];
  steps: string[];
}

export const CATEGORIES = [
  { id: "all", label: "All", emoji: "🧁" },
  { id: "cakes", label: "Cakes", emoji: "🎂" },
  { id: "cookies", label: "Cookies", emoji: "🍪" },
  { id: "muffins", label: "Muffins", emoji: "🧁" },
  { id: "pies", label: "Pies", emoji: "🥧" },
  { id: "bread", label: "Bread", emoji: "🍞" },
  { id: "donuts", label: "Donuts", emoji: "🍩" },
  { id: "pastries", label: "Pastries", emoji: "🥐" },
];

export const RECIPES: Recipe[] = [
  {
    id: "1",
    title: "Strawberry Dream Cake",
    category: "cakes",
    time: "45 min",
    difficulty: "Medium",
    rating: 4.8,
    servings: 8,
    image: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=600&h=600&fit=crop",
    description: "A fluffy vanilla sponge cake layered with fresh strawberry cream and topped with juicy strawberries. Pure heaven!",
    ingredients: [
      "2 cups all-purpose flour",
      "1½ cups granulated sugar",
      "3 large eggs",
      "1 cup whole milk",
      "½ cup unsalted butter, softened",
      "2 tsp vanilla extract",
      "2 tsp baking powder",
      "½ tsp salt",
      "2 cups fresh strawberries",
      "2 cups heavy whipping cream",
      "¼ cup powdered sugar",
      "Pink food coloring (optional)",
    ],
    steps: [
      "Preheat oven to 350°F (175°C). Grease and flour two 9-inch round cake pans.",
      "In a large bowl, cream butter and sugar until light and fluffy, about 3-4 minutes.",
      "Add eggs one at a time, beating well after each. Mix in vanilla extract.",
      "In a separate bowl, whisk flour, baking powder, and salt together.",
      "Alternate adding flour mixture and milk to the butter mixture, beginning and ending with flour. Mix until just combined.",
      "Divide batter between pans. Bake for 25-30 minutes until a toothpick comes out clean.",
      "Let cool completely. Meanwhile, whip cream with powdered sugar until stiff peaks form.",
      "Slice strawberries. Place one cake layer on plate, spread cream, add berries. Top with second layer.",
      "Cover entire cake with remaining whipped cream and decorate with whole strawberries.",
    ],
  },
  {
    id: "2",
    title: "Chocolate Chip Cookies",
    category: "cookies",
    time: "25 min",
    difficulty: "Easy",
    rating: 4.9,
    servings: 24,
    image: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=600&h=600&fit=crop",
    description: "Classic chewy chocolate chip cookies with crispy edges and gooey centers. The ultimate comfort bake!",
    ingredients: [
      "2¼ cups all-purpose flour",
      "1 cup butter, softened",
      "¾ cup granulated sugar",
      "¾ cup brown sugar, packed",
      "2 large eggs",
      "1 tsp vanilla extract",
      "1 tsp baking soda",
      "1 tsp salt",
      "2 cups semi-sweet chocolate chips",
    ],
    steps: [
      "Preheat oven to 375°F (190°C). Line baking sheets with parchment paper.",
      "Cream butter with both sugars until light and fluffy.",
      "Beat in eggs and vanilla until combined.",
      "Mix in flour, baking soda, and salt until just combined.",
      "Fold in chocolate chips.",
      "Drop rounded tablespoons onto prepared baking sheets, spacing 2 inches apart.",
      "Bake for 9-11 minutes until golden brown around edges but still soft in center.",
      "Cool on baking sheet for 5 minutes, then transfer to wire rack.",
    ],
  },
  {
    id: "3",
    title: "Blueberry Bliss Muffins",
    category: "muffins",
    time: "30 min",
    difficulty: "Easy",
    rating: 4.7,
    servings: 12,
    image: "https://images.unsplash.com/photo-1607958996333-41aef7caefaa?w=600&h=600&fit=crop",
    description: "Fluffy, tender muffins bursting with juicy blueberries and topped with a crunchy sugar streusel.",
    ingredients: [
      "2 cups all-purpose flour",
      "¾ cup sugar",
      "2 tsp baking powder",
      "½ tsp salt",
      "⅓ cup vegetable oil",
      "1 large egg",
      "1 cup milk",
      "1 tsp vanilla extract",
      "1½ cups fresh blueberries",
      "2 tbsp turbinado sugar (for topping)",
    ],
    steps: [
      "Preheat oven to 400°F (200°C). Line a 12-cup muffin tin with cute paper liners.",
      "Whisk flour, sugar, baking powder, and salt in a large bowl.",
      "In another bowl, mix oil, egg, milk, and vanilla.",
      "Pour wet ingredients into dry and stir until just combined (lumpy is okay!).",
      "Gently fold in blueberries.",
      "Divide batter among muffin cups. Sprinkle turbinado sugar on top.",
      "Bake 20-25 minutes until tops are golden and a toothpick comes out clean.",
      "Cool in pan 5 minutes, then transfer to wire rack.",
    ],
  },
  {
    id: "4",
    title: "Caramel Apple Pie",
    category: "pies",
    time: "90 min",
    difficulty: "Hard",
    rating: 4.9,
    servings: 8,
    image: "https://images.unsplash.com/photo-1568571780765-9276ac8b75a2?w=600&h=600&fit=crop",
    description: "A golden, flaky crust filled with cinnamon-spiced apples drizzled with homemade caramel. Pure autumn magic!",
    ingredients: [
      "2½ cups all-purpose flour",
      "1 cup cold unsalted butter, cubed",
      "¼ cup ice water",
      "6 large Granny Smith apples",
      "¾ cup sugar",
      "2 tbsp cinnamon",
      "1 tbsp lemon juice",
      "2 tbsp cornstarch",
      "½ cup caramel sauce",
      "1 egg (for egg wash)",
      "Pinch of salt",
    ],
    steps: [
      "Make crust: pulse flour, salt, and cold butter in food processor until pea-sized crumbs form. Add ice water gradually until dough comes together.",
      "Divide dough in half, flatten into disks, wrap in plastic, and chill for 1 hour.",
      "Peel, core, and slice apples. Toss with sugar, cinnamon, lemon juice, and cornstarch.",
      "Roll out one disk and fit into a 9-inch pie dish.",
      "Fill with apple mixture, drizzle caramel sauce over apples.",
      "Roll out second disk for top crust. Cut decorative vents or create a lattice pattern.",
      "Brush top with egg wash. Sprinkle with sugar.",
      "Bake at 375°F for 50-55 minutes until golden and bubbly.",
      "Cool at least 2 hours before slicing. Serve with vanilla ice cream!",
    ],
  },
  {
    id: "5",
    title: "Fluffy Cinnamon Rolls",
    category: "pastries",
    time: "120 min",
    difficulty: "Medium",
    rating: 4.8,
    servings: 12,
    image: "https://images.unsplash.com/photo-1609127845842-2e8e1080e52c?w=600&h=600&fit=crop",
    description: "Soft, pillowy cinnamon rolls swirled with brown sugar and cinnamon, topped with cream cheese frosting.",
    ingredients: [
      "4 cups all-purpose flour",
      "1 packet instant yeast",
      "1 cup warm milk",
      "⅓ cup sugar",
      "⅓ cup butter, melted",
      "2 eggs",
      "1 tsp salt",
      "1 cup brown sugar (filling)",
      "3 tbsp cinnamon (filling)",
      "⅓ cup softened butter (filling)",
      "4 oz cream cheese (frosting)",
      "2 cups powdered sugar (frosting)",
      "1 tsp vanilla (frosting)",
    ],
    steps: [
      "Warm milk to 110°F. Add yeast and a pinch of sugar. Let sit 5 minutes until foamy.",
      "Mix flour, sugar, and salt. Add yeast mixture, melted butter, and eggs. Knead 8 minutes until smooth.",
      "Place dough in greased bowl, cover, let rise 1 hour until doubled.",
      "Roll dough into a large rectangle. Spread softened butter, sprinkle brown sugar and cinnamon.",
      "Roll up tightly from the long side. Cut into 12 equal pieces.",
      "Place rolls in a greased 9x13 baking dish. Cover and let rise 30 minutes.",
      "Bake at 350°F for 22-25 minutes until golden.",
      "Make frosting: beat cream cheese, powdered sugar, and vanilla until smooth.",
      "Spread frosting over warm rolls and serve immediately!",
    ],
  },
  {
    id: "6",
    title: "Red Velvet Cupcakes",
    category: "cakes",
    time: "35 min",
    difficulty: "Easy",
    rating: 4.6,
    servings: 18,
    image: "https://images.unsplash.com/photo-1614707267537-b85aaf00c4b7?w=600&h=600&fit=crop",
    description: "Moist red velvet cupcakes with a hint of cocoa, crowned with swirls of tangy cream cheese frosting.",
    ingredients: [
      "1½ cups all-purpose flour",
      "1 cup sugar",
      "1 tsp baking soda",
      "1 tsp cocoa powder",
      "½ cup vegetable oil",
      "1 cup buttermilk",
      "2 large eggs",
      "2 tbsp red food coloring",
      "1 tsp vanilla extract",
      "1 tsp white vinegar",
      "8 oz cream cheese (frosting)",
      "½ cup butter, softened (frosting)",
      "3 cups powdered sugar (frosting)",
    ],
    steps: [
      "Preheat oven to 350°F. Line 18 muffin cups with adorable paper liners.",
      "Whisk flour, sugar, baking soda, and cocoa in a bowl.",
      "In another bowl, mix oil, buttermilk, eggs, food coloring, vanilla, and vinegar.",
      "Combine wet and dry ingredients until smooth.",
      "Fill liners ⅔ full. Bake 18-20 minutes until a toothpick comes out clean.",
      "Cool completely before frosting.",
      "Beat cream cheese and butter until smooth. Add powdered sugar and mix until fluffy.",
      "Pipe frosting on cooled cupcakes using a star tip. Add sprinkles!",
    ],
  },
  {
    id: "7",
    title: "Lemon Sugar Cookies",
    category: "cookies",
    time: "40 min",
    difficulty: "Easy",
    rating: 4.5,
    servings: 30,
    image: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600&h=600&fit=crop",
    description: "Buttery, melt-in-your-mouth sugar cookies with bright lemon zest and a sweet glaze.",
    ingredients: [
      "3 cups all-purpose flour",
      "1½ cups sugar",
      "1 cup butter, softened",
      "2 eggs",
      "2 tbsp lemon zest",
      "2 tbsp fresh lemon juice",
      "1 tsp vanilla extract",
      "1½ tsp baking powder",
      "½ tsp salt",
      "2 cups powdered sugar (glaze)",
      "3 tbsp lemon juice (glaze)",
      "Yellow food coloring (optional)",
    ],
    steps: [
      "Cream butter and sugar until fluffy. Add eggs, lemon zest, lemon juice, and vanilla.",
      "Mix in flour, baking powder, and salt until dough forms.",
      "Chill dough 30 minutes.",
      "Roll out to ¼ inch thick. Cut with cute cookie cutters (hearts, stars, flowers!).",
      "Bake at 350°F for 8-10 minutes until edges are barely golden.",
      "Cool completely. Mix glaze ingredients and drizzle or dip cookies.",
      "Decorate with sprinkles while glaze is still wet!",
    ],
  },
  {
    id: "8",
    title: "Banana Nut Bread",
    category: "bread",
    time: "60 min",
    difficulty: "Easy",
    rating: 4.7,
    servings: 10,
    image: "https://images.unsplash.com/photo-1605090930601-47a0e1e35810?w=600&h=600&fit=crop",
    description: "Super moist banana bread with toasted walnuts and a crackly sugar top. Best with overripe bananas!",
    ingredients: [
      "3 large ripe bananas, mashed",
      "⅓ cup melted butter",
      "¾ cup sugar",
      "1 egg, beaten",
      "1 tsp vanilla extract",
      "1 tsp baking soda",
      "Pinch of salt",
      "1½ cups all-purpose flour",
      "½ cup chopped walnuts",
    ],
    steps: [
      "Preheat oven to 350°F. Grease a 9x5 inch loaf pan.",
      "Mash bananas in a large bowl. Mix in melted butter.",
      "Stir in sugar, beaten egg, and vanilla.",
      "Add baking soda and salt. Mix in flour until just combined.",
      "Fold in chopped walnuts.",
      "Pour into prepared pan. Sprinkle extra sugar on top.",
      "Bake 55-60 minutes until golden and a toothpick comes out clean.",
      "Cool in pan 10 minutes, then turn out onto a wire rack. Slice and enjoy warm!",
    ],
  },
  {
    id: "9",
    title: "Glazed Donuts",
    category: "donuts",
    time: "50 min",
    difficulty: "Medium",
    rating: 4.8,
    servings: 12,
    image: "https://images.unsplash.com/photo-1551024601-bec78aea704b?w=600&h=600&fit=crop",
    description: "Light, airy yeast donuts with a shiny sweet glaze. Better than any donut shop!",
    ingredients: [
      "2¼ tsp active dry yeast",
      "¾ cup warm milk",
      "¼ cup sugar",
      "2½ cups all-purpose flour",
      "2 egg yolks",
      "3 tbsp butter, softened",
      "½ tsp salt",
      "Oil for frying",
      "2 cups powdered sugar (glaze)",
      "¼ cup milk (glaze)",
      "1 tsp vanilla (glaze)",
    ],
    steps: [
      "Dissolve yeast in warm milk with a pinch of sugar. Let sit 5 minutes.",
      "Mix flour, sugar, and salt. Add yeast mixture, egg yolks, and butter. Knead until smooth.",
      "Cover and let rise 1 hour until doubled.",
      "Roll dough to ½ inch thick. Cut with donut cutter.",
      "Let cut donuts rise 30 minutes on parchment paper.",
      "Heat oil to 350°F. Fry donuts 1-2 minutes per side until golden.",
      "Drain on paper towels briefly.",
      "Mix glaze ingredients until smooth. Dip warm donuts in glaze.",
      "Add sprinkles while glaze is wet. Let set on wire rack.",
    ],
  },
  {
    id: "10",
    title: "Matcha Swiss Roll",
    category: "cakes",
    time: "55 min",
    difficulty: "Hard",
    rating: 4.6,
    servings: 8,
    image: "https://images.unsplash.com/photo-1519915028121-7d3463d20b13?w=600&h=600&fit=crop",
    description: "A delicate matcha sponge cake rolled with silky vanilla whipped cream. Elegant and delicious!",
    ingredients: [
      "4 large eggs, separated",
      "½ cup sugar",
      "¾ cup cake flour",
      "2 tbsp matcha powder",
      "2 tbsp milk",
      "2 tbsp vegetable oil",
      "¼ tsp cream of tartar",
      "1½ cups heavy cream (filling)",
      "3 tbsp powdered sugar (filling)",
      "1 tsp vanilla extract (filling)",
    ],
    steps: [
      "Preheat oven to 325°F. Line a 10x15 jelly roll pan with parchment paper.",
      "Beat egg yolks with half the sugar until pale. Stir in milk and oil.",
      "Sift flour and matcha together, fold into yolk mixture gently.",
      "Beat egg whites with cream of tartar until foamy. Gradually add remaining sugar, beat to stiff peaks.",
      "Fold whites into matcha batter in 3 additions. Be very gentle!",
      "Pour into prepared pan, smooth top. Bake 12-15 minutes until springy.",
      "Immediately turn out onto a clean kitchen towel dusted with powdered sugar. Roll up with towel and cool.",
      "Whip cream with sugar and vanilla until stiff.",
      "Unroll cake, spread cream evenly, re-roll without the towel. Chill 1 hour before slicing.",
    ],
  },
  {
    id: "11",
    title: "Triple Berry Tart",
    category: "pies",
    time: "70 min",
    difficulty: "Medium",
    rating: 4.7,
    servings: 8,
    image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&h=600&fit=crop",
    description: "A buttery shortcrust tart filled with vanilla pastry cream and piled high with fresh berries.",
    ingredients: [
      "1¼ cups all-purpose flour",
      "½ cup powdered sugar",
      "½ cup cold butter, cubed",
      "1 egg yolk",
      "2 cups whole milk (pastry cream)",
      "½ cup sugar (pastry cream)",
      "4 egg yolks (pastry cream)",
      "3 tbsp cornstarch (pastry cream)",
      "1 tsp vanilla (pastry cream)",
      "1 cup fresh strawberries",
      "1 cup fresh blueberries",
      "½ cup fresh raspberries",
      "¼ cup apricot jam (glaze)",
    ],
    steps: [
      "Make tart crust: pulse flour, sugar, and butter until crumbly. Add egg yolk, press into tart pan.",
      "Prick with fork. Bake at 375°F for 15-18 minutes until golden. Cool completely.",
      "Make pastry cream: heat milk. Whisk yolks, sugar, and cornstarch. Temper with hot milk.",
      "Return to heat, cook until thick. Stir in vanilla. Cover with plastic wrap touching surface. Chill.",
      "Spread pastry cream in cooled tart shell.",
      "Arrange berries beautifully on top.",
      "Warm apricot jam, brush over berries for a gorgeous shine.",
      "Chill 30 minutes before serving. Dust with powdered sugar!",
    ],
  },
  {
    id: "12",
    title: "Croissants",
    category: "pastries",
    time: "180 min",
    difficulty: "Hard",
    rating: 4.9,
    servings: 8,
    image: "https://images.unsplash.com/photo-1555507036-ab1f4038024a?w=600&h=600&fit=crop",
    description: "Flaky, buttery, golden croissants with a million layers. Worth every minute of effort!",
    ingredients: [
      "3½ cups all-purpose flour",
      "⅓ cup sugar",
      "2¼ tsp instant yeast",
      "1½ tsp salt",
      "1¼ cups cold whole milk",
      "1 cup + 2 tbsp cold unsalted butter (for laminating)",
      "1 egg + 1 tbsp milk (egg wash)",
    ],
    steps: [
      "Mix flour, sugar, yeast, salt, and milk. Knead briefly. Chill 1 hour.",
      "Pound butter into a flat 6-inch square between parchment paper. Keep cold.",
      "Roll dough into a rectangle. Place butter in center, fold dough over butter to enclose.",
      "Roll out and perform first fold (letter fold). Chill 30 minutes.",
      "Repeat rolling and folding 2 more times, chilling between each fold.",
      "Roll dough to ¼ inch thick. Cut triangles and roll each from base to tip.",
      "Curve ends to form crescent shape. Place on lined baking sheet.",
      "Cover and proof 1½-2 hours until doubled and jiggly.",
      "Brush with egg wash. Bake at 400°F for 15-18 minutes until deep golden.",
    ],
  },
];
