export const COLORS = {
  // Dark kitty cat theme
  bg: "#1A1220",
  bgCard: "#251B2E",
  bgElevated: "#2E2339",
  bgInput: "#352A40",
  hotpink: "#FF69B4",
  pink: "#FF8DC7",
  lavender: "#C4B5FD",
  mint: "#6EE7B7",
  butter: "#FDE68A",
  blush: "#FFB6C1",
  rose: "#FF8FAB",
  cream: "#FFF0F5",
  lilac: "#D8B4FE",
  sky: "#93C5FD",
  coral: "#FB7185",
  peach: "#FDBA74",
  white: "#F8F0F6",
  dark: "#F0E6F0",
  gray: "#9B8DA8",
  lightGray: "#3D3248",
  accent: "#A855F7",
  gold: "#FBBF24",
  pro: "#F59E0B",
} as const;

export const SHADOWS = {
  soft: {
    shadowColor: "#FF69B4",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 4,
  },
  card: {
    shadowColor: "#A855F7",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 6,
  },
  button: {
    shadowColor: "#FF69B4",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 3,
  },
  glow: {
    shadowColor: "#C4B5FD",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 8,
  },
} as const;
