export { CATEGORIES } from "./types";
export type { Recipe } from "./types";

import { Recipe } from "./types";

export const RECIPES: Recipe[] = [
  {
    id: "1",
    title: "Strawberry Dream Cake",
    category: "cakes",
    time: "45 min",
    difficulty: "Medium",
    rating: 4.8,
    servings: 8,
    image: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=600&h=600&fit=crop",
    description: "A fluffy vanilla sponge cake layered with fresh strawberry cream and topped with juicy strawberries. Pure heaven!",
    ingredients: [
      "2 cups all-purpose flour",
      "1½ cups granulated sugar",
      "3 large eggs",
      "1 cup whole milk",
      "½ cup unsalted butter, softened",
      "2 tsp vanilla extract",
      "2 tsp baking powder",
      "½ tsp salt",
      "2 cups fresh strawberries",
      "2 cups heavy whipping cream",
      "¼ cup powdered sugar",
      "Pink food coloring (optional)",
    ],
    steps: [
      "Preheat oven to 350°F (175°C). Grease and flour two 9-inch round cake pans.",
      "In a large bowl, cream butter and sugar until light and fluffy, about 3-4 minutes.",
      "Add eggs one at a time, beating well after each. Mix in vanilla extract.",
      "In a separate bowl, whisk flour, baking powder, and salt together.",
      "Alternate adding flour mixture and milk to the butter mixture, beginning and ending with flour. Mix until just combined.",
      "Divide batter between pans. Bake for 25-30 minutes until a toothpick comes out clean.",
      "Let cool completely. Meanwhile, whip cream with powdered sugar until stiff peaks form.",
      "Slice strawberries. Place one cake layer on plate, spread cream, add berries. Top with second layer.",
      "Cover entire cake with remaining whipped cream and decorate with whole strawberries.",
    ],
  },
  {
    id: "2",
    title: "Chocolate Chip Cookies",
    category: "cookies",
    time: "25 min",
    difficulty: "Easy",
    rating: 4.9,
    servings: 24,
    image: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=600&h=600&fit=crop",
    description: "Classic chewy chocolate chip cookies with crispy edges and gooey centers. The ultimate comfort bake!",
    ingredients: [
      "2¼ cups all-purpose flour",
      "1 cup butter, softened",
      "¾ cup granulated sugar",
      "¾ cup brown sugar, packed",
      "2 large eggs",
      "1 tsp vanilla extract",
      "1 tsp baking soda",
      "1 tsp salt",
      "2 cups semi-sweet chocolate chips",
    ],
    steps: [
      "Preheat oven to 375°F (190°C). Line baking sheets with parchment paper.",
      "Cream butter with both sugars until light and fluffy.",
      "Beat in eggs and vanilla until combined.",
      "Mix in flour, baking soda, and salt until just combined.",
      "Fold in chocolate chips.",
      "Drop rounded tablespoons onto prepared baking sheets, spacing 2 inches apart.",
      "Bake for 9-11 minutes until golden brown around edges but still soft in center.",
      "Cool on baking sheet for 5 minutes, then transfer to wire rack.",
    ],
  },
  {
    id: "3",
    title: "Blueberry Bliss Muffins",
    category: "muffins",
    time: "30 min",
    difficulty: "Easy",
    rating: 4.7,
    servings: 12,
    image: "https://images.unsplash.com/photo-1607958996333-41aef7caefaa?w=600&h=600&fit=crop",
    description: "Fluffy, tender muffins bursting with juicy blueberries and topped with a crunchy sugar streusel.",
    ingredients: [
      "2 cups all-purpose flour",
      "¾ cup sugar",
      "2 tsp baking powder",
      "½ tsp salt",
      "⅓ cup vegetable oil",
      "1 large egg",
      "1 cup milk",
      "1 tsp vanilla extract",
      "1½ cups fresh blueberries",
      "2 tbsp turbinado sugar (for topping)",
    ],
    steps: [
      "Preheat oven to 400°F (200°C). Line a 12-cup muffin tin with cute paper liners.",
      "Whisk flour, sugar, baking powder, and salt in a large bowl.",
      "In another bowl, mix oil, egg, milk, and vanilla.",
      "Pour wet ingredients into dry and stir until just combined (lumpy is okay!).",
      "Gently fold in blueberries.",
      "Divide batter among muffin cups. Sprinkle turbinado sugar on top.",
      "Bake 20-25 minutes until tops are golden and a toothpick comes out clean.",
      "Cool in pan 5 minutes, then transfer to wire rack.",
    ],
  },
  {
    id: "4",
    title: "Caramel Apple Pie",
    category: "pies",
    time: "90 min",
    difficulty: "Hard",
    rating: 4.9,
    servings: 8,
    image: "https://images.unsplash.com/photo-1568571780765-9276ac8b75a2?w=600&h=600&fit=crop",
    description: "A golden, flaky crust filled with cinnamon-spiced apples drizzled with homemade caramel. Pure autumn magic!",
    ingredients: [
      "2½ cups all-purpose flour",
      "1 cup cold unsalted butter, cubed",
      "¼ cup ice water",
      "6 large Granny Smith apples",
      "¾ cup sugar",
      "2 tbsp cinnamon",
      "1 tbsp lemon juice",
      "2 tbsp cornstarch",
      "½ cup caramel sauce",
      "1 egg (for egg wash)",
      "Pinch of salt",
    ],
    steps: [
      "Make crust: pulse flour, salt, and cold butter in food processor until pea-sized crumbs form. Add ice water gradually until dough comes together.",
      "Divide dough in half, flatten into disks, wrap in plastic, and chill for 1 hour.",
      "Peel, core, and slice apples. Toss with sugar, cinnamon, lemon juice, and cornstarch.",
      "Roll out one disk and fit into a 9-inch pie dish.",
      "Fill with apple mixture, drizzle caramel sauce over apples.",
      "Roll out second disk for top crust. Cut decorative vents or create a lattice pattern.",
      "Brush top with egg wash. Sprinkle with sugar.",
      "Bake at 375°F for 50-55 minutes until golden and bubbly.",
      "Cool at least 2 hours before slicing. Serve with vanilla ice cream!",
    ],
  },
  {
    id: "5",
    title: "Fluffy Cinnamon Rolls",
    category: "pastries",
    time: "120 min",
    difficulty: "Medium",
    rating: 4.8,
    servings: 12,
    image: "https://images.unsplash.com/photo-1609127845842-2e8e1080e52c?w=600&h=600&fit=crop",
    description: "Soft, pillowy cinnamon rolls swirled with brown sugar and cinnamon, topped with cream cheese frosting.",
    ingredients: [
      "4 cups all-purpose flour",
      "1 packet instant yeast",
      "1 cup warm milk",
      "⅓ cup sugar",
      "⅓ cup butter, melted",
      "2 eggs",
      "1 tsp salt",
      "1 cup brown sugar (filling)",
      "3 tbsp cinnamon (filling)",
      "⅓ cup softened butter (filling)",
      "4 oz cream cheese (frosting)",
      "2 cups powdered sugar (frosting)",
      "1 tsp vanilla (frosting)",
    ],
    steps: [
      "Warm milk to 110°F. Add yeast and a pinch of sugar. Let sit 5 minutes until foamy.",
      "Mix flour, sugar, and salt. Add yeast mixture, melted butter, and eggs. Knead 8 minutes until smooth.",
      "Place dough in greased bowl, cover, let rise 1 hour until doubled.",
      "Roll dough into a large rectangle. Spread softened butter, sprinkle brown sugar and cinnamon.",
      "Roll up tightly from the long side. Cut into 12 equal pieces.",
      "Place rolls in a greased 9x13 baking dish. Cover and let rise 30 minutes.",
      "Bake at 350°F for 22-25 minutes until golden.",
      "Make frosting: beat cream cheese, powdered sugar, and vanilla until smooth.",
      "Spread frosting over warm rolls and serve immediately!",
    ],
  },
  {
    id: "6",
    title: "Red Velvet Cupcakes",
    category: "cakes",
    time: "35 min",
    difficulty: "Easy",
    rating: 4.6,
    servings: 18,
    image: "https://images.unsplash.com/photo-1614707267537-b85aaf00c4b7?w=600&h=600&fit=crop",
    description: "Moist red velvet cupcakes with a hint of cocoa, crowned with swirls of tangy cream cheese frosting.",
    ingredients: [
      "1½ cups all-purpose flour",
      "1 cup sugar",
      "1 tsp baking soda",
      "1 tsp cocoa powder",
      "½ cup vegetable oil",
      "1 cup buttermilk",
      "2 large eggs",
      "2 tbsp red food coloring",
      "1 tsp vanilla extract",
      "1 tsp white vinegar",
      "8 oz cream cheese (frosting)",
      "½ cup butter, softened (frosting)",
      "3 cups powdered sugar (frosting)",
    ],
    steps: [
      "Preheat oven to 350°F. Line 18 muffin cups with adorable paper liners.",
      "Whisk flour, sugar, baking soda, and cocoa in a bowl.",
      "In another bowl, mix oil, buttermilk, eggs, food coloring, vanilla, and vinegar.",
      "Combine wet and dry ingredients until smooth.",
      "Fill liners ⅔ full. Bake 18-20 minutes until a toothpick comes out clean.",
      "Cool completely before frosting.",
      "Beat cream cheese and butter until smooth. Add powdered sugar and mix until fluffy.",
      "Pipe frosting on cooled cupcakes using a star tip. Add sprinkles!",
    ],
  },
  {
    id: "7",
    title: "Lemon Sugar Cookies",
    category: "cookies",
    time: "40 min",
    difficulty: "Easy",
    rating: 4.5,
    servings: 30,
    image: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600&h=600&fit=crop",
    description: "Buttery, melt-in-your-mouth sugar cookies with bright lemon zest and a sweet glaze.",
    ingredients: [
      "3 cups all-purpose flour",
      "1½ cups sugar",
      "1 cup butter, softened",
      "2 eggs",
      "2 tbsp lemon zest",
      "2 tbsp fresh lemon juice",
      "1 tsp vanilla extract",
      "1½ tsp baking powder",
      "½ tsp salt",
      "2 cups powdered sugar (glaze)",
      "3 tbsp lemon juice (glaze)",
      "Yellow food coloring (optional)",
    ],
    steps: [
      "Cream butter and sugar until fluffy. Add eggs, lemon zest, lemon juice, and vanilla.",
      "Mix in flour, baking powder, and salt until dough forms.",
      "Chill dough 30 minutes.",
      "Roll out to ¼ inch thick. Cut with cute cookie cutters (hearts, stars, flowers!).",
      "Bake at 350°F for 8-10 minutes until edges are barely golden.",
      "Cool completely. Mix glaze ingredients and drizzle or dip cookies.",
      "Decorate with sprinkles while glaze is still wet!",
    ],
  },
  {
    id: "8",
    title: "Banana Nut Bread",
    category: "bread",
    time: "60 min",
    difficulty: "Easy",
    rating: 4.7,
    servings: 10,
    image: "https://images.unsplash.com/photo-1605090930601-47a0e1e35810?w=600&h=600&fit=crop",
    description: "Super moist banana bread with toasted walnuts and a crackly sugar top. Best with overripe bananas!",
    ingredients: [
      "3 large ripe bananas, mashed",
      "⅓ cup melted butter",
      "¾ cup sugar",
      "1 egg, beaten",
      "1 tsp vanilla extract",
      "1 tsp baking soda",
      "Pinch of salt",
      "1½ cups all-purpose flour",
      "½ cup chopped walnuts",
    ],
    steps: [
      "Preheat oven to 350°F. Grease a 9x5 inch loaf pan.",
      "Mash bananas in a large bowl. Mix in melted butter.",
      "Stir in sugar, beaten egg, and vanilla.",
      "Add baking soda and salt. Mix in flour until just combined.",
      "Fold in chopped walnuts.",
      "Pour into prepared pan. Sprinkle extra sugar on top.",
      "Bake 55-60 minutes until golden and a toothpick comes out clean.",
      "Cool in pan 10 minutes, then turn out onto a wire rack. Slice and enjoy warm!",
    ],
  },
  {
    id: "9",
    title: "Glazed Donuts",
    category: "donuts",
    time: "50 min",
    difficulty: "Medium",
    rating: 4.8,
    servings: 12,
    image: "https://images.unsplash.com/photo-1551024601-bec78aea704b?w=600&h=600&fit=crop",
    description: "Light, airy yeast donuts with a shiny sweet glaze. Better than any donut shop!",
    ingredients: [
      "2¼ tsp active dry yeast",
      "¾ cup warm milk",
      "¼ cup sugar",
      "2½ cups all-purpose flour",
      "2 egg yolks",
      "3 tbsp butter, softened",
      "½ tsp salt",
      "Oil for frying",
      "2 cups powdered sugar (glaze)",
      "¼ cup milk (glaze)",
      "1 tsp vanilla (glaze)",
    ],
    steps: [
      "Dissolve yeast in warm milk with a pinch of sugar. Let sit 5 minutes.",
      "Mix flour, sugar, and salt. Add yeast mixture, egg yolks, and butter. Knead until smooth.",
      "Cover and let rise 1 hour until doubled.",
      "Roll dough to ½ inch thick. Cut with donut cutter.",
      "Let cut donuts rise 30 minutes on parchment paper.",
      "Heat oil to 350°F. Fry donuts 1-2 minutes per side until golden.",
      "Drain on paper towels briefly.",
      "Mix glaze ingredients until smooth. Dip warm donuts in glaze.",
      "Add sprinkles while glaze is wet. Let set on wire rack.",
    ],
  },
  {
    id: "10",
    title: "Matcha Swiss Roll",
    category: "cakes",
    time: "55 min",
    difficulty: "Hard",
    rating: 4.6,
    servings: 8,
    image: "https://images.unsplash.com/photo-1519915028121-7d3463d20b13?w=600&h=600&fit=crop",
    description: "A delicate matcha sponge cake rolled with silky vanilla whipped cream. Elegant and delicious!",
    ingredients: [
      "4 large eggs, separated",
      "½ cup sugar",
      "¾ cup cake flour",
      "2 tbsp matcha powder",
      "2 tbsp milk",
      "2 tbsp vegetable oil",
      "¼ tsp cream of tartar",
      "1½ cups heavy cream (filling)",
      "3 tbsp powdered sugar (filling)",
      "1 tsp vanilla extract (filling)",
    ],
    steps: [
      "Preheat oven to 325°F. Line a 10x15 jelly roll pan with parchment paper.",
      "Beat egg yolks with half the sugar until pale. Stir in milk and oil.",
      "Sift flour and matcha together, fold into yolk mixture gently.",
      "Beat egg whites with cream of tartar until foamy. Gradually add remaining sugar, beat to stiff peaks.",
      "Fold whites into matcha batter in 3 additions. Be very gentle!",
      "Pour into prepared pan, smooth top. Bake 12-15 minutes until springy.",
      "Immediately turn out onto a clean kitchen towel dusted with powdered sugar. Roll up with towel and cool.",
      "Whip cream with sugar and vanilla until stiff.",
      "Unroll cake, spread cream evenly, re-roll without the towel. Chill 1 hour before slicing.",
    ],
  },
  {
    id: "11",
    title: "Triple Berry Tart",
    category: "pies",
    time: "70 min",
    difficulty: "Medium",
    rating: 4.7,
    servings: 8,
    image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&h=600&fit=crop",
    description: "A buttery shortcrust tart filled with vanilla pastry cream and piled high with fresh berries.",
    ingredients: [
      "1¼ cups all-purpose flour",
      "½ cup powdered sugar",
      "½ cup cold butter, cubed",
      "1 egg yolk",
      "2 cups whole milk (pastry cream)",
      "½ cup sugar (pastry cream)",
      "4 egg yolks (pastry cream)",
      "3 tbsp cornstarch (pastry cream)",
      "1 tsp vanilla (pastry cream)",
      "1 cup fresh strawberries",
      "1 cup fresh blueberries",
      "½ cup fresh raspberries",
      "¼ cup apricot jam (glaze)",
    ],
    steps: [
      "Make tart crust: pulse flour, sugar, and butter until crumbly. Add egg yolk, press into tart pan.",
      "Prick with fork. Bake at 375°F for 15-18 minutes until golden. Cool completely.",
      "Make pastry cream: heat milk. Whisk yolks, sugar, and cornstarch. Temper with hot milk.",
      "Return to heat, cook until thick. Stir in vanilla. Cover with plastic wrap touching surface. Chill.",
      "Spread pastry cream in cooled tart shell.",
      "Arrange berries beautifully on top.",
      "Warm apricot jam, brush over berries for a gorgeous shine.",
      "Chill 30 minutes before serving. Dust with powdered sugar!",
    ],
  },
  {
    id: "12",
    title: "Croissants",
    category: "pastries",
    time: "180 min",
    difficulty: "Hard",
    rating: 4.9,
    servings: 8,
    image: "https://images.unsplash.com/photo-1555507036-ab1f4038024a?w=600&h=600&fit=crop",
    description: "Flaky, buttery, golden croissants with a million layers. Worth every minute of effort!",
    ingredients: [
      "3½ cups all-purpose flour",
      "⅓ cup sugar",
      "2¼ tsp instant yeast",
      "1½ tsp salt",
      "1¼ cups cold whole milk",
      "1 cup + 2 tbsp cold unsalted butter (for laminating)",
      "1 egg + 1 tbsp milk (egg wash)",
    ],
    steps: [
      "Mix flour, sugar, yeast, salt, and milk. Knead briefly. Chill 1 hour.",
      "Pound butter into a flat 6-inch square between parchment paper. Keep cold.",
      "Roll dough into a rectangle. Place butter in center, fold dough over butter to enclose.",
      "Roll out and perform first fold (letter fold). Chill 30 minutes.",
      "Repeat rolling and folding 2 more times, chilling between each fold.",
      "Roll dough to ¼ inch thick. Cut triangles and roll each from base to tip.",
      "Curve ends to form crescent shape. Place on lined baking sheet.",
      "Cover and proof 1½-2 hours until doubled and jiggly.",
      "Brush with egg wash. Bake at 400°F for 15-18 minutes until deep golden.",
    ],
  },
  // ===== BROWNIES =====
  {
    id: "13",
    title: "Classic Fudgy Brownies",
    category: "brownies",
    time: "35 min",
    difficulty: "Easy",
    rating: 4.8,
    servings: 16,
    image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&h=600&fit=crop",
    description: "Rich, fudgy brownies with a crackly top and impossibly gooey center. Chocolate lovers rejoice!",
    ingredients: [
      "½ cup unsalted butter",
      "1 cup granulated sugar",
      "2 large eggs",
      "1 tsp vanilla extract",
      "⅓ cup cocoa powder",
      "½ cup all-purpose flour",
      "¼ tsp salt",
      "¼ tsp baking powder",
    ],
    steps: [
      "Preheat oven to 350°F. Grease an 8x8 inch baking pan and line with parchment.",
      "Melt butter in a saucepan. Remove from heat and stir in sugar.",
      "Add eggs one at a time, stirring well after each. Mix in vanilla.",
      "Sift in cocoa powder, flour, salt, and baking powder. Fold until just combined.",
      "Pour batter into prepared pan and smooth the top.",
      "Bake 20-25 minutes until a toothpick comes out with moist crumbs.",
      "Cool completely in pan before cutting into squares.",
    ],
  },
  {
    id: "14",
    title: "Peanut Butter Swirl Brownies",
    category: "brownies",
    time: "40 min",
    difficulty: "Medium",
    rating: 4.7,
    servings: 16,
    image: "https://images.unsplash.com/photo-1612886623828-c2e699d67d53?w=600&h=600&fit=crop",
    description: "Decadent chocolate brownies with ribbons of creamy peanut butter swirled throughout!",
    ingredients: [
      "½ cup unsalted butter",
      "1 cup granulated sugar",
      "2 large eggs",
      "1 tsp vanilla extract",
      "⅓ cup cocoa powder",
      "½ cup all-purpose flour",
      "¼ tsp salt",
      "¼ tsp baking powder",
      "½ cup creamy peanut butter",
      "2 tbsp powdered sugar",
      "2 tbsp milk",
    ],
    steps: [
      "Preheat oven to 350°F. Line an 8x8 pan with parchment.",
      "Melt butter, stir in sugar, eggs, and vanilla.",
      "Fold in cocoa, flour, salt, and baking powder.",
      "In a small bowl, mix peanut butter, powdered sugar, and milk until smooth.",
      "Pour brownie batter into pan. Drop spoonfuls of peanut butter mixture on top.",
      "Use a knife to swirl the peanut butter into the chocolate batter.",
      "Bake 25-28 minutes. Cool completely before slicing.",
    ],
  },
  // ===== CUPCAKES =====
  {
    id: "15",
    title: "Vanilla Bean Cupcakes",
    category: "cupcakes",
    time: "30 min",
    difficulty: "Easy",
    rating: 4.7,
    servings: 12,
    image: "https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?w=600&h=600&fit=crop",
    description: "Light, fluffy vanilla cupcakes with a cloud of vanilla buttercream. Simple perfection!",
    ingredients: [
      "1½ cups all-purpose flour",
      "1 cup granulated sugar",
      "½ cup unsalted butter, softened",
      "2 large eggs",
      "½ cup whole milk",
      "2 tsp vanilla extract",
      "1½ tsp baking powder",
      "¼ tsp salt",
      "1 cup butter, softened (frosting)",
      "3 cups powdered sugar (frosting)",
      "2 tbsp heavy cream (frosting)",
      "1 tsp vanilla extract (frosting)",
    ],
    steps: [
      "Preheat oven to 350°F. Line a 12-cup muffin tin with pretty liners.",
      "Cream butter and sugar until light and fluffy.",
      "Add eggs one at a time, then vanilla.",
      "Whisk flour, baking powder, and salt. Alternate adding with milk.",
      "Fill liners ⅔ full. Bake 18-22 minutes until a toothpick comes out clean.",
      "Cool completely on wire rack.",
      "Beat frosting butter until creamy. Add powdered sugar, cream, and vanilla.",
      "Pipe big swirls of frosting on each cupcake!",
    ],
  },
  {
    id: "16",
    title: "Chocolate Fudge Cupcakes",
    category: "cupcakes",
    time: "35 min",
    difficulty: "Easy",
    rating: 4.8,
    servings: 18,
    image: "https://images.unsplash.com/photo-1587668178277-295251f900ce?w=600&h=600&fit=crop",
    description: "Intensely chocolatey cupcakes with a silky chocolate ganache frosting. Death by chocolate!",
    ingredients: [
      "1½ cups all-purpose flour",
      "1 cup granulated sugar",
      "½ cup cocoa powder",
      "1 tsp baking soda",
      "½ tsp salt",
      "1 cup hot coffee",
      "½ cup vegetable oil",
      "2 large eggs",
      "1 tsp vanilla extract",
      "½ cup buttermilk",
      "1 cup dark chocolate chips (ganache)",
      "½ cup heavy cream (ganache)",
    ],
    steps: [
      "Preheat oven to 350°F. Line 18 muffin cups with liners.",
      "Whisk flour, sugar, cocoa, baking soda, and salt.",
      "Add hot coffee, oil, eggs, vanilla, and buttermilk. Mix until smooth.",
      "Fill liners ⅔ full. Bake 16-18 minutes.",
      "Cool completely.",
      "Make ganache: heat cream, pour over chocolate chips. Stir until smooth.",
      "Let ganache cool slightly, then spread or pipe onto cupcakes.",
    ],
  },
  // ===== CHEESECAKES =====
  {
    id: "17",
    title: "New York Cheesecake",
    category: "cheesecakes",
    time: "90 min",
    difficulty: "Hard",
    rating: 4.9,
    servings: 12,
    image: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=600&h=600&fit=crop",
    description: "Tall, dense, and ultra-creamy New York style cheesecake with a buttery graham cracker crust.",
    ingredients: [
      "2 cups graham cracker crumbs",
      "⅓ cup granulated sugar (crust)",
      "½ cup unsalted butter, melted (crust)",
      "32 oz cream cheese, softened",
      "1 cup granulated sugar",
      "5 large eggs",
      "2 tsp vanilla extract",
      "¼ cup all-purpose flour",
      "1 cup sour cream",
      "¼ cup heavy cream",
      "1 tbsp lemon juice",
    ],
    steps: [
      "Preheat oven to 325°F. Wrap outside of a 9-inch springform pan in foil.",
      "Mix graham crumbs, sugar, and melted butter. Press firmly into bottom.",
      "Bake crust 10 minutes. Let cool.",
      "Beat cream cheese and sugar until very smooth.",
      "Add eggs one at a time on low speed. Mix in vanilla, flour, sour cream, heavy cream, lemon juice.",
      "Pour filling over crust. Place in a water bath.",
      "Bake 60-70 minutes until edges are set but center still jiggles.",
      "Turn oven off, crack door open, let cool in oven 1 hour.",
      "Refrigerate at least 4 hours before serving.",
    ],
  },
  {
    id: "18",
    title: "Strawberry Cheesecake Bars",
    category: "cheesecakes",
    time: "60 min",
    difficulty: "Medium",
    rating: 4.7,
    servings: 16,
    image: "https://images.unsplash.com/photo-1567171466295-4afa63d45416?w=600&h=600&fit=crop",
    description: "Creamy cheesecake bars with a swirl of fresh strawberry sauce on a buttery shortbread crust.",
    ingredients: [
      "1½ cups all-purpose flour",
      "½ cup powdered sugar",
      "¾ cup cold unsalted butter, cubed",
      "16 oz cream cheese, softened",
      "½ cup granulated sugar",
      "2 large eggs",
      "1 tsp vanilla extract",
      "1 cup fresh strawberries",
      "2 tbsp granulated sugar (sauce)",
      "1 tbsp lemon juice",
    ],
    steps: [
      "Preheat oven to 350°F. Line a 9x13 pan with parchment.",
      "Pulse flour, powdered sugar, and butter until crumbly. Press into pan.",
      "Bake crust 15 minutes until light golden.",
      "Beat cream cheese and sugar until smooth. Add eggs and vanilla.",
      "Blend strawberries with sugar and lemon juice until smooth.",
      "Pour cheesecake over crust. Drop spoonfuls of strawberry sauce and swirl.",
      "Bake 25-30 minutes until set. Cool, then chill at least 2 hours.",
    ],
  },
  // ===== SCONES =====
  {
    id: "19",
    title: "Classic Cream Scones",
    category: "scones",
    time: "25 min",
    difficulty: "Easy",
    rating: 4.6,
    servings: 8,
    image: "https://images.unsplash.com/photo-1583338917451-face2751d8d5?w=600&h=600&fit=crop",
    description: "Tender, flaky scones with a golden crust and soft interior. Perfect with tea and jam!",
    ingredients: [
      "2 cups all-purpose flour",
      "⅓ cup granulated sugar",
      "1 tbsp baking powder",
      "½ tsp salt",
      "½ cup cold unsalted butter, cubed",
      "½ cup heavy cream",
      "1 large egg",
      "1 tsp vanilla extract",
      "2 tbsp turbinado sugar (topping)",
    ],
    steps: [
      "Preheat oven to 400°F. Line a baking sheet with parchment.",
      "Whisk flour, sugar, baking powder, and salt.",
      "Cut in cold butter using a pastry cutter until pea-sized pieces remain.",
      "Mix cream, egg, and vanilla. Pour into flour mixture and stir until just combined.",
      "Pat dough into a circle about 1 inch thick. Cut into 8 wedges.",
      "Place on baking sheet. Sprinkle turbinado sugar on top.",
      "Bake 14-16 minutes until golden brown.",
      "Serve warm with butter, jam, or clotted cream!",
    ],
  },
  {
    id: "20",
    title: "Blueberry Lemon Scones",
    category: "scones",
    time: "30 min",
    difficulty: "Easy",
    rating: 4.8,
    servings: 8,
    image: "https://images.unsplash.com/photo-1486887396153-fa416526c108?w=600&h=600&fit=crop",
    description: "Flaky scones bursting with blueberries and drizzled with a tangy lemon glaze.",
    ingredients: [
      "2 cups all-purpose flour",
      "⅓ cup granulated sugar",
      "1 tbsp baking powder",
      "½ tsp salt",
      "½ cup cold unsalted butter, cubed",
      "½ cup heavy cream",
      "1 large egg",
      "2 tbsp lemon zest",
      "1 cup fresh blueberries",
      "1 cup powdered sugar (glaze)",
      "2 tbsp fresh lemon juice (glaze)",
    ],
    steps: [
      "Preheat oven to 400°F. Line a baking sheet with parchment.",
      "Whisk flour, sugar, baking powder, salt, and lemon zest.",
      "Cut in cold butter until crumbly.",
      "Mix cream and egg, pour into dry ingredients. Stir until just combined.",
      "Gently fold in blueberries.",
      "Shape into a disk, cut into 8 wedges.",
      "Bake 16-18 minutes until golden.",
      "Mix glaze ingredients. Drizzle over cooled scones.",
    ],
  },
  {
    id: "21",
    title: "Cranberry Orange Scones",
    category: "scones",
    time: "30 min",
    difficulty: "Easy",
    rating: 4.7,
    servings: 8,
    image: "https://images.unsplash.com/photo-1508737027454-e6454ef45afd?w=600&h=600&fit=crop",
    description: "Buttery scones with tart cranberries and bright orange zest. Holiday vibes all year!",
    ingredients: [
      "2 cups all-purpose flour",
      "⅓ cup granulated sugar",
      "1 tbsp baking powder",
      "½ tsp salt",
      "½ cup cold unsalted butter, cubed",
      "½ cup heavy cream",
      "1 large egg",
      "2 tbsp orange zest",
      "¾ cup dried cranberries",
      "1 cup powdered sugar (glaze)",
      "2 tbsp fresh orange juice (glaze)",
    ],
    steps: [
      "Preheat oven to 400°F. Line a baking sheet with parchment.",
      "Whisk flour, sugar, baking powder, salt, and orange zest.",
      "Cut in cold butter until crumbly.",
      "Mix cream and egg, add to dry ingredients. Stir until just combined.",
      "Fold in dried cranberries.",
      "Shape into a disk, cut into 8 wedges.",
      "Bake 15-18 minutes until golden.",
      "Mix glaze ingredients. Drizzle over cooled scones.",
    ],
  },
  // ===== MORE COOKIES =====
  {
    id: "22",
    title: "Snickerdoodles",
    category: "cookies",
    time: "25 min",
    difficulty: "Easy",
    rating: 4.7,
    servings: 24,
    image: "https://images.unsplash.com/photo-1590080875852-ba44f1e5bfbd?w=600&h=600&fit=crop",
    description: "Soft, pillowy cookies rolled in cinnamon sugar with a signature tangy flavor!",
    ingredients: [
      "2¾ cups all-purpose flour",
      "2 tsp cream of tartar",
      "1 tsp baking soda",
      "½ tsp salt",
      "1 cup unsalted butter, softened",
      "1½ cups granulated sugar",
      "2 large eggs",
      "1 tsp vanilla extract",
      "3 tbsp granulated sugar (coating)",
      "2 tsp cinnamon (coating)",
    ],
    steps: [
      "Preheat oven to 375°F. Line baking sheets with parchment.",
      "Whisk flour, cream of tartar, baking soda, and salt.",
      "Cream butter and sugar until fluffy. Beat in eggs and vanilla.",
      "Mix in dry ingredients until just combined.",
      "Combine coating sugar and cinnamon in a small bowl.",
      "Roll dough into 1-inch balls, then roll in cinnamon sugar.",
      "Place 2 inches apart on baking sheets.",
      "Bake 10-12 minutes until edges are set but centers are soft.",
    ],
  },
  {
    id: "23",
    title: "Peanut Butter Cookies",
    category: "cookies",
    time: "20 min",
    difficulty: "Easy",
    rating: 4.8,
    servings: 24,
    image: "https://images.unsplash.com/photo-1590080876351-941da357b7fa?w=600&h=600&fit=crop",
    description: "Soft and chewy peanut butter cookies with the classic crosshatch pattern!",
    ingredients: [
      "1 cup creamy peanut butter",
      "¾ cup granulated sugar",
      "¾ cup brown sugar, packed",
      "1 large egg",
      "1 tsp baking soda",
      "1 tsp vanilla extract",
      "1 cup all-purpose flour",
      "½ tsp salt",
    ],
    steps: [
      "Preheat oven to 350°F. Line baking sheets with parchment.",
      "Mix peanut butter, both sugars, egg, baking soda, and vanilla until smooth.",
      "Stir in flour and salt until combined.",
      "Roll into 1-inch balls and place on sheets.",
      "Press a crosshatch pattern with a fork dipped in sugar.",
      "Bake 10-12 minutes until lightly golden.",
      "Cool on sheet 5 minutes, then move to wire rack.",
    ],
  },
  {
    id: "24",
    title: "Double Chocolate Cookies",
    category: "cookies",
    time: "25 min",
    difficulty: "Easy",
    rating: 4.9,
    servings: 20,
    image: "https://images.unsplash.com/photo-1548365328-8c6db3220e4c?w=600&h=600&fit=crop",
    description: "Intensely chocolatey cookies that are crispy outside and fudgy inside!",
    ingredients: [
      "1¼ cups all-purpose flour",
      "½ cup cocoa powder",
      "1 tsp baking soda",
      "½ tsp salt",
      "½ cup unsalted butter, softened",
      "¾ cup granulated sugar",
      "½ cup brown sugar, packed",
      "1 large egg",
      "1 tsp vanilla extract",
      "1½ cups semi-sweet chocolate chips",
    ],
    steps: [
      "Preheat oven to 350°F. Line baking sheets with parchment.",
      "Whisk flour, cocoa, baking soda, and salt.",
      "Cream butter with both sugars. Beat in egg and vanilla.",
      "Mix in dry ingredients until just combined.",
      "Fold in chocolate chips.",
      "Drop rounded tablespoons onto sheets.",
      "Bake 10-12 minutes until set around edges.",
      "Cool on sheet 5 minutes. They firm up as they cool!",
    ],
  },
  {
    id: "25",
    title: "Oatmeal Raisin Cookies",
    category: "cookies",
    time: "25 min",
    difficulty: "Easy",
    rating: 4.6,
    servings: 24,
    image: "https://images.unsplash.com/photo-1490567674767-e6c07e250100?w=600&h=600&fit=crop",
    description: "Chewy oatmeal cookies studded with plump raisins and warm cinnamon!",
    ingredients: [
      "1 cup unsalted butter, softened",
      "¾ cup brown sugar, packed",
      "½ cup granulated sugar",
      "2 large eggs",
      "1 tsp vanilla extract",
      "1½ cups all-purpose flour",
      "1 tsp baking soda",
      "1 tsp cinnamon",
      "½ tsp salt",
      "3 cups old-fashioned oats",
      "1 cup raisins",
    ],
    steps: [
      "Preheat oven to 350°F. Line sheets with parchment.",
      "Cream butter and both sugars. Beat in eggs and vanilla.",
      "Mix in flour, baking soda, cinnamon, and salt.",
      "Stir in oats and raisins.",
      "Drop rounded tablespoons onto sheets.",
      "Bake 10-12 minutes until golden.",
      "Cool on sheet 5 minutes, then transfer to rack.",
    ],
  },
  // ===== MORE CAKES =====
  {
    id: "26",
    title: "Chocolate Lava Cakes",
    category: "cakes",
    time: "25 min",
    difficulty: "Medium",
    rating: 4.9,
    servings: 4,
    image: "https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=600&h=600&fit=crop",
    description: "Individual chocolate cakes with a warm, molten center that flows like lava!",
    ingredients: [
      "4 oz dark chocolate, chopped",
      "½ cup unsalted butter",
      "1 cup powdered sugar",
      "2 large eggs",
      "2 egg yolks",
      "6 tbsp all-purpose flour",
      "1 tsp vanilla extract",
      "Pinch of salt",
      "Cocoa powder (for dusting ramekins)",
    ],
    steps: [
      "Preheat oven to 425°F. Butter four 6-oz ramekins and dust with cocoa powder.",
      "Melt chocolate and butter together. Stir until smooth.",
      "Whisk in powdered sugar until combined.",
      "Add eggs and yolks, whisk well. Stir in vanilla.",
      "Fold in flour and salt until just combined.",
      "Divide among ramekins. Place on a baking sheet.",
      "Bake exactly 12-14 minutes until edges are firm but center is soft.",
      "Let sit 1 minute, then invert onto plates. Serve immediately with ice cream!",
    ],
  },
  {
    id: "27",
    title: "Carrot Cake",
    category: "cakes",
    time: "55 min",
    difficulty: "Medium",
    rating: 4.8,
    servings: 12,
    image: "https://images.unsplash.com/photo-1621303837174-89787a7d4729?w=600&h=600&fit=crop",
    description: "Moist, spiced carrot cake with toasted pecans and luscious cream cheese frosting.",
    ingredients: [
      "2 cups all-purpose flour",
      "2 cups granulated sugar",
      "2 tsp baking soda",
      "2 tsp cinnamon",
      "½ tsp nutmeg",
      "½ tsp salt",
      "1¼ cups vegetable oil",
      "4 large eggs",
      "3 cups grated carrots",
      "1 cup chopped pecans",
      "1 tsp vanilla extract",
      "8 oz cream cheese, softened (frosting)",
      "½ cup butter, softened (frosting)",
      "3 cups powdered sugar (frosting)",
    ],
    steps: [
      "Preheat oven to 350°F. Grease two 9-inch round cake pans.",
      "Mix flour, sugar, baking soda, cinnamon, nutmeg, and salt.",
      "Add oil, eggs, and vanilla. Beat until combined.",
      "Fold in grated carrots and pecans.",
      "Divide between pans. Bake 30-35 minutes.",
      "Cool completely in pans, then turn out.",
      "Beat cream cheese and butter for frosting. Add powdered sugar.",
      "Frost between layers, on top, and around sides.",
    ],
  },
  {
    id: "28",
    title: "Tiramisu",
    category: "cakes",
    time: "40 min",
    difficulty: "Medium",
    rating: 4.9,
    servings: 9,
    image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600&h=600&fit=crop",
    description: "Layers of espresso-soaked ladyfingers and mascarpone cream, dusted with cocoa. Italian perfection!",
    ingredients: [
      "6 large egg yolks",
      "¾ cup granulated sugar",
      "16 oz cream cheese, softened",
      "2 cups heavy cream",
      "2 tsp vanilla extract",
      "2 cups strong brewed coffee, cooled",
      "24 ladyfinger cookies",
      "3 tbsp cocoa powder (dusting)",
    ],
    steps: [
      "Beat egg yolks and sugar until thick and pale, about 4 minutes.",
      "Add cream cheese and mix until smooth.",
      "In another bowl, whip cream and vanilla to stiff peaks.",
      "Fold whipped cream into cream cheese mixture gently.",
      "Quickly dip ladyfingers in coffee. Layer in 8x8 dish.",
      "Spread half the cream mixture over ladyfingers.",
      "Repeat layers. Dust generously with cocoa powder.",
      "Cover and refrigerate at least 6 hours.",
    ],
  },
  // ===== MORE BREAD =====
  {
    id: "29",
    title: "Pumpkin Bread",
    category: "bread",
    time: "65 min",
    difficulty: "Easy",
    rating: 4.7,
    servings: 10,
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&h=600&fit=crop",
    description: "Warmly spiced pumpkin bread that fills your kitchen with the coziest autumn aroma!",
    ingredients: [
      "1¾ cups all-purpose flour",
      "1½ cups granulated sugar",
      "1 tsp baking soda",
      "½ tsp baking powder",
      "½ tsp salt",
      "1 tsp cinnamon",
      "½ tsp nutmeg",
      "¼ tsp ground cloves",
      "1 cup canned pumpkin puree",
      "½ cup vegetable oil",
      "2 large eggs",
      "1 tsp vanilla extract",
    ],
    steps: [
      "Preheat oven to 350°F. Grease a 9x5 loaf pan.",
      "Whisk flour, sugar, baking soda, baking powder, salt, and all spices.",
      "In another bowl, mix pumpkin, oil, eggs, and vanilla.",
      "Pour wet into dry and stir until just combined.",
      "Pour into prepared pan.",
      "Bake 55-65 minutes until a toothpick comes out clean.",
      "Cool in pan 10 minutes, then turn out onto wire rack.",
    ],
  },
  {
    id: "30",
    title: "Zucchini Bread",
    category: "bread",
    time: "60 min",
    difficulty: "Easy",
    rating: 4.6,
    servings: 10,
    image: "https://images.unsplash.com/photo-1595535973496-da5ccc369999?w=600&h=600&fit=crop",
    description: "Incredibly moist zucchini bread with a hint of cinnamon. A delicious way to use garden zucchini!",
    ingredients: [
      "2 cups all-purpose flour",
      "1½ cups granulated sugar",
      "1 tsp baking soda",
      "½ tsp baking powder",
      "1 tsp salt",
      "1 tsp cinnamon",
      "2 cups grated zucchini",
      "¾ cup vegetable oil",
      "2 large eggs",
      "1 tsp vanilla extract",
      "½ cup chopped walnuts (optional)",
    ],
    steps: [
      "Preheat oven to 350°F. Grease a 9x5 loaf pan.",
      "Whisk flour, sugar, baking soda, baking powder, salt, and cinnamon.",
      "Squeeze excess moisture from grated zucchini.",
      "Mix oil, eggs, vanilla, and zucchini in another bowl.",
      "Combine wet and dry ingredients. Fold in walnuts if using.",
      "Pour into pan. Bake 55-60 minutes until golden.",
      "Cool 10 minutes in pan, then remove to wire rack.",
    ],
  },
  // ===== MORE MUFFINS =====
  {
    id: "31",
    title: "Lemon Poppy Seed Muffins",
    category: "muffins",
    time: "28 min",
    difficulty: "Easy",
    rating: 4.6,
    servings: 12,
    image: "https://images.unsplash.com/photo-1558303452-a51b0a3660a0?w=600&h=600&fit=crop",
    description: "Bright and tangy muffins studded with poppy seeds and drizzled with a sweet lemon glaze.",
    ingredients: [
      "2 cups all-purpose flour",
      "¾ cup granulated sugar",
      "2 tsp baking powder",
      "½ tsp salt",
      "2 tbsp poppy seeds",
      "⅓ cup vegetable oil",
      "1 large egg",
      "1 cup milk",
      "3 tbsp fresh lemon juice",
      "2 tbsp lemon zest",
      "1 cup powdered sugar (glaze)",
      "2 tbsp lemon juice (glaze)",
    ],
    steps: [
      "Preheat oven to 400°F. Line muffin tin with liners.",
      "Whisk flour, sugar, baking powder, salt, and poppy seeds.",
      "Mix oil, egg, milk, lemon juice, and zest.",
      "Combine wet and dry until just mixed.",
      "Fill liners ⅔ full. Bake 18-20 minutes until golden.",
      "Cool. Mix glaze ingredients and drizzle over muffins.",
    ],
  },
  {
    id: "32",
    title: "Chocolate Chip Muffins",
    category: "muffins",
    time: "25 min",
    difficulty: "Easy",
    rating: 4.7,
    servings: 12,
    image: "https://images.unsplash.com/photo-1604882356758-536eca5e23c8?w=600&h=600&fit=crop",
    description: "Bakery-style jumbo muffins loaded with chocolate chips and topped with a sugar crunch.",
    ingredients: [
      "2 cups all-purpose flour",
      "¾ cup granulated sugar",
      "2½ tsp baking powder",
      "½ tsp salt",
      "⅓ cup vegetable oil",
      "1 large egg",
      "1 cup milk",
      "1 tsp vanilla extract",
      "1½ cups semi-sweet chocolate chips",
    ],
    steps: [
      "Preheat oven to 400°F. Line muffin tin with paper liners.",
      "Whisk flour, sugar, baking powder, and salt.",
      "Mix oil, egg, milk, and vanilla in another bowl.",
      "Pour wet into dry, stir until just combined.",
      "Fold in chocolate chips (reserve a few for tops).",
      "Fill liners to the top for big, domed muffins.",
      "Top with reserved chips. Bake 18-22 minutes.",
    ],
  },
  // ===== MORE PIES =====
  {
    id: "33",
    title: "Pecan Pie",
    category: "pies",
    time: "70 min",
    difficulty: "Medium",
    rating: 4.8,
    servings: 10,
    image: "https://images.unsplash.com/photo-1574085733277-851d9d856a3a?w=600&h=600&fit=crop",
    description: "Gooey, caramelly pecan pie with a buttery crust. A classic Southern dessert!",
    ingredients: [
      "1¼ cups all-purpose flour",
      "½ cup cold unsalted butter, cubed",
      "¼ cup ice water",
      "½ tsp salt",
      "3 large eggs",
      "1 cup corn syrup",
      "½ cup brown sugar, packed",
      "¼ cup unsalted butter, melted",
      "1 tsp vanilla extract",
      "2 cups pecan halves",
    ],
    steps: [
      "Make crust: mix flour and salt, cut in cold butter, add water until dough forms. Chill 30 min.",
      "Roll out dough and fit into a 9-inch pie dish.",
      "Preheat oven to 350°F.",
      "Whisk eggs, corn syrup, brown sugar, melted butter, and vanilla.",
      "Arrange pecans in crust. Pour filling over pecans.",
      "Bake 45-50 minutes until set around edges.",
      "Cool completely before slicing. Serve with whipped cream!",
    ],
  },
  {
    id: "34",
    title: "Key Lime Pie",
    category: "pies",
    time: "45 min",
    difficulty: "Medium",
    rating: 4.7,
    servings: 8,
    image: "https://images.unsplash.com/photo-1535920527002-b35e96722eb9?w=600&h=600&fit=crop",
    description: "Tangy, creamy key lime filling in a crunchy graham cracker crust topped with whipped cream.",
    ingredients: [
      "1½ cups graham cracker crumbs",
      "⅓ cup granulated sugar",
      "6 tbsp unsalted butter, melted",
      "3 egg yolks",
      "2 cans (14 oz each) sweetened condensed milk",
      "¾ cup fresh lime juice",
      "1 tbsp lime zest",
      "1½ cups heavy cream (topping)",
      "3 tbsp powdered sugar (topping)",
    ],
    steps: [
      "Preheat oven to 350°F.",
      "Mix graham crumbs, sugar, and melted butter. Press into a 9-inch pie dish.",
      "Bake crust 8 minutes. Let cool.",
      "Whisk egg yolks, condensed milk, lime juice, and zest until smooth.",
      "Pour into cooled crust. Bake 15 minutes until just set.",
      "Cool to room temperature, then refrigerate at least 4 hours.",
      "Whip cream with powdered sugar. Pile on top of pie.",
    ],
  },
  // ===== MORE DONUTS =====
  {
    id: "35",
    title: "Apple Cider Donuts",
    category: "donuts",
    time: "35 min",
    difficulty: "Easy",
    rating: 4.8,
    servings: 12,
    image: "https://images.unsplash.com/photo-1509461399763-ae67a981b254?w=600&h=600&fit=crop",
    description: "Baked apple cider donuts coated in cinnamon sugar. Like visiting an orchard in fall!",
    ingredients: [
      "2 cups all-purpose flour",
      "1½ tsp baking powder",
      "½ tsp baking soda",
      "½ tsp salt",
      "2 tsp cinnamon",
      "½ tsp nutmeg",
      "½ cup apple cider",
      "½ cup granulated sugar",
      "¼ cup unsalted butter, melted",
      "¼ cup sour cream",
      "1 large egg",
      "1 tsp vanilla extract",
      "¼ cup butter, melted (coating)",
      "½ cup granulated sugar (coating)",
      "1 tbsp cinnamon (coating)",
    ],
    steps: [
      "Preheat oven to 350°F. Grease a donut pan well.",
      "Whisk flour, baking powder, baking soda, salt, cinnamon, and nutmeg.",
      "Mix apple cider, sugar, melted butter, sour cream, egg, and vanilla.",
      "Combine wet and dry ingredients until just mixed.",
      "Pipe or spoon batter into donut pan, filling ⅔ full.",
      "Bake 10-12 minutes until donuts spring back when touched.",
      "Mix coating sugar and cinnamon in a bowl.",
      "Brush warm donuts with melted butter, then roll in cinnamon sugar.",
    ],
  },
  // ===== TARTS =====
  {
    id: "36",
    title: "Chocolate Ganache Tart",
    category: "tarts",
    time: "45 min",
    difficulty: "Medium",
    rating: 4.8,
    servings: 8,
    image: "https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?w=600&h=600&fit=crop",
    description: "A crisp chocolate cookie crust filled with silky smooth dark chocolate ganache. Pure elegance!",
    ingredients: [
      "1¼ cups all-purpose flour",
      "¼ cup cocoa powder",
      "½ cup powdered sugar",
      "½ cup cold unsalted butter, cubed",
      "1 egg yolk",
      "1 tbsp cold water",
      "10 oz dark chocolate, chopped",
      "1 cup heavy cream",
      "2 tbsp unsalted butter",
      "1 tsp vanilla extract",
    ],
    steps: [
      "Pulse flour, cocoa, sugar, and cold butter until sandy. Add yolk and water, press into tart pan.",
      "Prick bottom with fork. Freeze 15 minutes.",
      "Bake at 375°F for 15-18 minutes. Cool.",
      "Heat cream until simmering. Pour over chopped chocolate.",
      "Let sit 2 minutes, then stir until smooth. Add butter and vanilla.",
      "Pour ganache into tart shell. Smooth top.",
      "Chill at least 2 hours until set. Serve at room temperature.",
    ],
  },
  {
    id: "37",
    title: "Lemon Curd Tart",
    category: "tarts",
    time: "50 min",
    difficulty: "Medium",
    rating: 4.7,
    servings: 8,
    image: "https://images.unsplash.com/photo-1519340241574-2cec6aef0c01?w=600&h=600&fit=crop",
    description: "A buttery shell filled with bright, tangy homemade lemon curd. Sunshine in every bite!",
    ingredients: [
      "1¼ cups all-purpose flour",
      "½ cup powdered sugar",
      "½ cup cold unsalted butter, cubed",
      "1 egg yolk",
      "4 large eggs (curd)",
      "1 cup granulated sugar (curd)",
      "¾ cup fresh lemon juice (curd)",
      "2 tbsp lemon zest (curd)",
      "½ cup unsalted butter, cubed (curd)",
    ],
    steps: [
      "Pulse flour, powdered sugar, butter until crumbly. Add yolk, press into tart pan.",
      "Prick bottom, chill 20 minutes. Bake at 375°F for 15 minutes.",
      "Make curd: whisk eggs, sugar, lemon juice, and zest over medium heat.",
      "Stir constantly until thickened, about 8-10 minutes.",
      "Remove from heat, whisk in butter until smooth.",
      "Pour curd into baked shell. Smooth top.",
      "Chill at least 3 hours until set.",
    ],
  },
  // ===== MORE PASTRIES =====
  {
    id: "38",
    title: "French Macarons",
    category: "pastries",
    time: "90 min",
    difficulty: "Hard",
    rating: 4.9,
    servings: 24,
    image: "https://images.unsplash.com/photo-1569864358642-9d1684040f43?w=600&h=600&fit=crop",
    description: "Delicate, colorful French macarons with smooth tops, ruffled feet, and creamy filling.",
    ingredients: [
      "1¾ cups powdered sugar",
      "1 cup almond flour",
      "3 large egg whites, room temperature",
      "¼ cup granulated sugar",
      "½ tsp vanilla extract",
      "Food coloring (gel, any color)",
      "½ cup unsalted butter, softened (filling)",
      "1½ cups powdered sugar (filling)",
      "1 tbsp heavy cream (filling)",
    ],
    steps: [
      "Sift powdered sugar and almond flour together twice.",
      "Beat egg whites to foamy. Gradually add granulated sugar, beat to stiff, glossy peaks.",
      "Add vanilla and food coloring. Fold in almond mixture in 3 additions.",
      "Batter should flow like lava, making a figure 8 without breaking.",
      "Pipe 1.5-inch circles onto parchment-lined sheets.",
      "Tap sheets firmly on counter. Pop any air bubbles with a toothpick.",
      "Let rest 30-60 minutes until shells form a dry skin.",
      "Bake at 300°F for 14-16 minutes. Cool completely.",
      "Make filling: beat butter, powdered sugar, cream. Pipe between shells.",
    ],
  },
  {
    id: "39",
    title: "Cream Puffs",
    category: "pastries",
    time: "60 min",
    difficulty: "Hard",
    rating: 4.8,
    servings: 12,
    image: "https://images.unsplash.com/photo-1509365465985-25d11c17e812?w=600&h=600&fit=crop",
    description: "Light, crispy choux shells filled with vanilla pastry cream and dusted with powdered sugar.",
    ingredients: [
      "½ cup unsalted butter",
      "1 cup water",
      "¼ tsp salt",
      "1 cup all-purpose flour",
      "4 large eggs",
      "2 cups whole milk (filling)",
      "½ cup granulated sugar (filling)",
      "3 egg yolks (filling)",
      "3 tbsp cornstarch (filling)",
      "2 tbsp butter (filling)",
      "1 tsp vanilla (filling)",
      "Powdered sugar (dusting)",
    ],
    steps: [
      "Preheat oven to 425°F. Line baking sheets with parchment.",
      "Heat butter, water, and salt until boiling. Add flour all at once.",
      "Stir vigorously until dough pulls away from sides. Cook 1 more minute.",
      "Transfer to mixer. Add eggs one at a time, beating well after each.",
      "Pipe 2-inch mounds onto sheets. Bake 15 min at 425°F, then 10 min at 350°F.",
      "Make pastry cream: heat milk. Whisk yolks, sugar, cornstarch. Temper with hot milk.",
      "Return to pot, cook until thick. Stir in butter and vanilla. Chill.",
      "Cut puffs in half, pipe filling inside. Dust with powdered sugar!",
    ],
  },
  // ===== MORE CHEESECAKE =====
  {
    id: "40",
    title: "Marble Cheesecake",
    category: "cheesecakes",
    time: "80 min",
    difficulty: "Medium",
    rating: 4.8,
    servings: 12,
    image: "https://images.unsplash.com/photo-1578775887804-699de7086502?w=600&h=600&fit=crop",
    description: "Creamy vanilla cheesecake with gorgeous swirls of rich chocolate throughout!",
    ingredients: [
      "1½ cups graham cracker crumbs",
      "¼ cup granulated sugar (crust)",
      "⅓ cup unsalted butter, melted (crust)",
      "24 oz cream cheese, softened",
      "¾ cup granulated sugar",
      "3 large eggs",
      "1 cup sour cream",
      "1 tsp vanilla extract",
      "3 oz dark chocolate, melted",
      "2 tbsp cocoa powder",
    ],
    steps: [
      "Preheat oven to 325°F. Mix crumbs, sugar, butter. Press into springform pan.",
      "Bake crust 10 minutes. Cool.",
      "Beat cream cheese and sugar until smooth. Add eggs one at a time.",
      "Mix in sour cream and vanilla.",
      "Remove 1 cup of batter. Stir melted chocolate and cocoa into it.",
      "Pour vanilla batter over crust. Drop spoonfuls of chocolate batter on top.",
      "Use a knife to swirl into a marble pattern.",
      "Bake 50-55 minutes. Cool slowly in oven with door cracked. Chill overnight.",
    ],
  },
  // ===== COCONUT MACAROONS =====
  {
    id: "41",
    title: "Coconut Macaroons",
    category: "cookies",
    time: "25 min",
    difficulty: "Easy",
    rating: 4.6,
    servings: 20,
    image: "https://images.unsplash.com/photo-1558312657-b2dead03d494?w=600&h=600&fit=crop",
    description: "Crispy outside, chewy inside coconut cookies dipped in dark chocolate.",
    ingredients: [
      "14 oz sweetened shredded coconut",
      "14 oz sweetened condensed milk",
      "2 large egg whites",
      "1 tsp vanilla extract",
      "¼ tsp almond extract",
      "¼ tsp salt",
      "6 oz dark chocolate, melted (for dipping)",
    ],
    steps: [
      "Preheat oven to 325°F. Line sheets with parchment.",
      "Mix coconut, condensed milk, vanilla, almond extract, and salt.",
      "Beat egg whites to stiff peaks. Fold into coconut mixture gently.",
      "Drop rounded tablespoons onto sheets, shaping into mounds.",
      "Bake 20-22 minutes until golden on edges.",
      "Cool completely.",
      "Dip bottoms in melted chocolate. Place on parchment to set.",
    ],
  },
  // ===== TRES LECHES =====
  {
    id: "42",
    title: "Tres Leches Cake",
    category: "cakes",
    time: "50 min",
    difficulty: "Medium",
    rating: 4.7,
    servings: 12,
    image: "https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e?w=600&h=600&fit=crop",
    description: "A light sponge soaked in three milks and topped with fluffy whipped cream. Melt-in-your-mouth!",
    ingredients: [
      "1 cup all-purpose flour",
      "1½ tsp baking powder",
      "5 large eggs",
      "1 cup granulated sugar",
      "⅓ cup whole milk",
      "1 tsp vanilla extract",
      "1 can (14 oz) sweetened condensed milk",
      "1 can (12 oz) evaporated milk",
      "1 cup heavy cream",
      "2 cups heavy whipping cream (topping)",
      "3 tbsp granulated sugar (topping)",
      "1 tsp cinnamon (garnish)",
    ],
    steps: [
      "Preheat oven to 350°F. Grease a 9x13 baking dish.",
      "Whisk flour and baking powder. Separate eggs.",
      "Beat yolks with ¾ cup sugar until thick. Stir in milk and vanilla.",
      "Beat whites to soft peaks, add remaining sugar, beat to stiff peaks.",
      "Fold yolk mixture into whites, then fold in flour gently.",
      "Pour into pan. Bake 25-30 minutes until golden.",
      "Mix condensed milk, evaporated milk, and 1 cup cream. Poke holes in warm cake.",
      "Pour milk mixture over cake slowly. Refrigerate at least 4 hours.",
      "Whip topping cream with sugar. Spread over cake, sprinkle cinnamon.",
    ],
  },
  // ===== GARLIC BREAD =====
  {
    id: "43",
    title: "Garlic Pull-Apart Bread",
    category: "bread",
    time: "75 min",
    difficulty: "Medium",
    rating: 4.8,
    servings: 8,
    image: "https://images.unsplash.com/photo-1549931319-a545753467c8?w=600&h=600&fit=crop",
    description: "Warm, buttery pull-apart bread loaded with garlic and herbs. Dangerously addictive!",
    ingredients: [
      "3 cups all-purpose flour",
      "1 packet instant yeast",
      "1 cup warm milk",
      "2 tbsp granulated sugar",
      "3 tbsp unsalted butter, melted",
      "1 tsp salt",
      "½ cup butter, melted (garlic butter)",
      "4 cloves garlic, minced",
      "2 tbsp fresh parsley, chopped",
    ],
    steps: [
      "Mix flour, yeast, sugar, and salt. Add warm milk and melted butter. Knead 8 minutes.",
      "Cover and let rise 45 minutes until doubled.",
      "Mix melted butter, garlic, and parsley.",
      "Punch down dough. Roll out and cut into small squares.",
      "Dip each piece in garlic butter and layer in a greased bundt or loaf pan.",
      "Let rise 20 minutes. Bake at 350°F for 25-30 minutes until golden.",
      "Invert onto a plate and serve warm. Pull apart and enjoy!",
    ],
  },
  // ===== CHOCOLATE DONUTS =====
  {
    id: "44",
    title: "Chocolate Glazed Donuts",
    category: "donuts",
    time: "55 min",
    difficulty: "Medium",
    rating: 4.7,
    servings: 12,
    image: "https://images.unsplash.com/photo-1551106652-a5bcf4b29ab6?w=600&h=600&fit=crop",
    description: "Pillowy yeast donuts dipped in rich chocolate glaze and topped with colorful sprinkles!",
    ingredients: [
      "2¼ tsp active dry yeast",
      "¾ cup warm milk",
      "¼ cup granulated sugar",
      "2½ cups all-purpose flour",
      "2 egg yolks",
      "3 tbsp butter, softened",
      "½ tsp salt",
      "Oil for frying",
      "1 cup dark chocolate chips (glaze)",
      "½ cup heavy cream (glaze)",
      "Sprinkles for topping",
    ],
    steps: [
      "Dissolve yeast in warm milk with a pinch of sugar. Wait 5 minutes.",
      "Mix flour, sugar, salt. Add yeast mixture, egg yolks, and butter. Knead until smooth.",
      "Cover, let rise 1 hour.",
      "Roll out to ½ inch, cut with donut cutter.",
      "Let donuts rise 30 minutes.",
      "Fry in 350°F oil, 1-2 minutes per side.",
      "Heat cream, pour over chocolate chips to make ganache. Stir smooth.",
      "Dip tops of cooled donuts in ganache. Add sprinkles!",
    ],
  },
];
